# -*- coding: utf-8 -*-
"""WG《肌能訓練》＋ FITT-VP：名詞小辭典（category 訓練科學）"""
CAT = "訓練科學"
LOAD = {"src": "assets/diagrams/load-zones.svg", "caption": "%1RM ↔ 次數：1–6 肌力／7–12 肌肥大／12–15 肌耐力"}
ENERGY = {"src": "assets/diagrams/energy-systems.svg", "caption": "三大能量系統：磷快、糖中、氧慢久"}
HR = {"src": "assets/diagrams/hr-zones.svg", "caption": "影片 5 心率區間＋Karvonen 步驟（補充公式）"}
FITT = {"src": "assets/fitt-vp-table.jpg", "caption": "FITT-VP 運動處方表（學員提供；文字版見 L24）"}

def t(id, term, aliases, one, explain, example, related=(), lessons=(), mns=(), hy=True, diagram=None):
    d = {"id": id, "term": term, "aliases": list(aliases), "category": CAT, "oneLiner": one,
         "explain": list(explain), "example": example, "relatedIds": list(related),
         "lessonIds": list(lessons), "mnemonicIds": list(mns), "highYield": hy}
    if diagram:
        d["diagram"] = diagram
    return d

TERMS = [
    t("term-muscle-training", "肌能訓練", [], "WG 影片定義：肌力 ＋ 能量系統的訓練。",
      ["一半在練「力氣」（肌力、肌肥大、肌耐力），一半在練「供電系統」（磷酸肌酸、糖解、有氧）。"],
      "重訓練肌力、跑步間歇練能量系統，兩者都屬肌能訓練。", ["term-strength", "term-pcr"], ["L21", "L22"], ["mn-wgmt-rep-zones"], False),
    t("term-strength", "肌力", ["muscular strength"], "肌肉收縮產生力量的能力。",
      ["看的是「一次能出多大力」。WG 負荷表：1–6 下（約 85–100%1RM）偏練肌力。"],
      "把一箱 24 瓶礦泉水從地上搬起來。", ["term-1rm", "term-hypertrophy", "term-endurance"], ["L21", "L22"], ["mn-wgmt-rep-zones"]),
    t("term-1rm", "1RM", ["一次最大反覆", "1 RM", "最大肌力重量"], "用標準動作「只能舉起 1 下」的重量。",
      ["RM＝Repetition Maximum（最大反覆次數）。1RM 是每個人、每個動作各自不同的數字。", "知道 1RM 後就能用 %1RM 換算訓練重量。"],
      "深蹲 100 公斤只能蹲起 1 下 → 深蹲 1RM＝100 公斤。", ["term-rm", "term-pct-1rm"], ["L21"], ["mn-wgmt-1rm"], True, LOAD),
    t("term-rm", "RM（最大反覆次數）", ["Repetition Maximum", "10RM", "最大反覆次數"], "「剛好只能做 N 下」的重量就叫 N RM。",
      ["1RM＝只能做 1 下的重量；10RM＝剛好只能做 10 下的重量（〔補充〕同一套說法）。", "FITT-VP 表阻力強度寫「%RM」，進展寫「漸增阻力或 RM」。"],
      "某重量你做到第 10 下就做不動了 → 那是你的 10RM。", ["term-1rm", "term-pct-1rm"], ["L21", "L24"], ["mn-wgmt-1rm"]),
    t("term-pct-1rm", "%1RM", ["百分比 1RM", "%RM"], "把 1RM 當 100%，換算出要用的重量比例。",
      ["算法：重量＝1RM × 百分比。", "WG 表：100%≈1 下、90%≈4 下、80%≈8 下、75%≈10 下、67%≈12 下、65%≈15 下。"],
      "1RM 60 公斤 × 65%＝39 公斤。", ["term-1rm", "term-rpe"], ["L21", "L24"], ["mn-wgmt-1rm", "mn-wgmt-rep-zones"], True, LOAD),
    t("term-hypertrophy", "肌肥大", ["hypertrophy", "增肌"], "肌肉變粗、變大。",
      ["WG 影片：阻力訓練破壞肌纖維 → 靠營養與休息重建 → 變粗。", "WG 負荷表：7–12 下（約 67–83%1RM）。"],
      "像道路挖開後重鋪時順便拓寬；肌肉是在吃飽睡好時長的。", ["term-strength", "term-mech-tension", "term-recovery"], ["L21"], ["mn-wgmt-rep-zones"]),
    t("term-endurance", "肌耐力", ["muscular endurance"], "肌肉可以持續使用的時間變長。",
      ["WG 負荷表：12–15 下（約 65–67%1RM，自覺「輕」）。"],
      "抱小孩抱很久手不痠；爬很多層樓腿不軟。", ["term-strength", "term-hypertrophy"], ["L21", "L22"], ["mn-wgmt-rep-zones"]),
    t("term-rpe", "自覺強度", ["自覺量表", "RPE", "自覺用力程度"], "你自己主觀覺得「有多重／多累」。",
      ["WG 表標示：輕（65%）、稍微重（77%）、重（83%）、非常重（90%）、非常非常重（100%）。", "FITT-VP 表阻力強度可用「%RM、自覺量表」。〔補充〕英文常寫 RPE。"],
      "沒測 1RM 的新手，可以先用「覺得重、還能多做 1–2 下」來抓重量。", ["term-pct-1rm"], ["L21", "L24"], ["mn-wgmt-rep-zones"]),
    t("term-mech-tension", "機械張力", ["mechanical tension"], "肌肉在出力時「被拉緊」的程度；影片說肌肉只感受得到張力，不是重量。",
      ["WG：好的機械張力＝低速度、高重量。", "是影響肌力／肌肥大的 7 因素之一。"],
      "同一袋米慢慢抱上來比甩上去，手臂要一直撐，張力比較持續。", ["term-metabolic-stress", "term-hypertrophy"], ["L21"], ["mn-wgmt-mech-slow-heavy"]),
    t("term-metabolic-stress", "代謝壓力", ["metabolic stress"], "大量代謝、乳酸堆積的情境，逼身體去適應。",
      ["7 因素之一。常出現在連續做很多下、休息很短時。"],
      "做到肌肉「燒燒的」那種感覺。", ["term-lactate", "term-mech-tension"], ["L21"], ["mn-wgmt-7factors"]),
    t("term-neural-adapt", "神經適應", ["神經學效能", "neural adaptation"], "大腦學會一次徵召更多運動單位，所以力氣先變大。",
      ["WG：初學者肌力先升、肌肉還沒長＝神經適應。", "是 7 因素裡的「神經學效能」。"],
      "員工人數沒變，但老闆學會一次叫更多人一起搬貨。", ["term-motor-unit", "term-strength"], ["L21"], ["mn-wgmt-neural-first"]),
    t("term-motor-unit", "運動單位", ["motor unit"], "〔補充〕一條運動神經 ＋ 它負責指揮的那一群肌纖維。",
      ["出力越大，大腦就要「徵召」（叫出來工作）越多運動單位。"],
      "像一個小組長帶一組工人；要搬重物就要叫出更多小組。", ["term-neural-adapt"], ["L21"], ["mn-wgmt-neural-first"], False),
    t("term-hormones", "激素水準", ["激素", "荷爾蒙", "睪固酮", "生長激素"], "身體裡傳訊息的化學物質多寡；影響肌力與肌肥大。",
      ["WG：影響最大的是睪固酮、生長激素。"],
      "同樣練法，激素水準不同的人，長肌肉速度可能不同。", ["term-hypertrophy"], ["L21"], ["mn-wgmt-7factors"], True),
    t("term-recovery", "身體恢復率", ["恢復率"], "身體從訓練中修復的速度；WG：靠吃、睡。",
      ["7 因素之一。肌肥大是在恢復期間發生的。", "FITT-VP 表阻力：同一肌群至少休息 48 小時。"],
      "熬夜又沒吃蛋白質，練得再認真也長得慢。", ["term-hypertrophy"], ["L21", "L24"], ["mn-wgmt-7factors", "mn-wgmt-res-48"]),
    t("term-bone-density", "骨密度", ["bone density"], "骨頭裡礦物質有多紮實；越高越不容易骨折。",
      ["WG：阻力訓練可以增加骨密度與結締組織強度。"],
      "長輩做適度重訓，有助骨頭更結實。", ["term-connective", "term-resistance-training"], ["L21"], ["mn-wgmt-benefits5"], False),
    t("term-insulin-sens", "胰島素敏感度", ["胰島素"], "身體對胰島素（幫血糖進入細胞的荷爾蒙）反應好不好。",
      ["敏感度好＝血糖比較好控制。WG：阻力訓練能改善血糖控制與胰島素敏感度。"],
      "同樣吃一碗飯，敏感度好的人血糖比較快回穩。", ["term-blood-glucose", "term-resistance-training"], ["L21"], ["mn-wgmt-benefits5"], False),
    t("term-connective", "結締組織", [], "把身體各部位連起來、撐起來的組織，例如肌腱、韌帶、筋膜。",
      ["WG：阻力訓練增加骨密度與結締組織強度。"],
      "肌腱把肌肉接到骨頭上，韌帶把骨頭跟骨頭綁在一起。", ["term-bone-density"], ["L21"], ["mn-wgmt-benefits5"], False),
    t("term-resistance-training", "阻力訓練", ["重量訓練", "重訓", "resistance training"], "讓肌肉對抗阻力（重量、彈力帶、自身體重）的訓練。",
      ["WG 5 優點：肌力爆發耐力↑、骨密度結締組織↑、降受傷抗老、改善血糖與胰島素敏感度、增肌降脂。", "FITT-VP 表：每週 2–3 次、同肌群隔 48 小時。"],
      "啞鈴、器械、伏地挺身都算。", ["term-1rm", "term-hypertrophy"], ["L21", "L24"], ["mn-wgmt-benefits5", "mn-wgmt-res-48"]),
    t("term-health-fitness", "健康體適能", ["健康體適能五要素"], "為了健康、每個人都需要的 5 項體能。",
      ["心肺功能、肌力、肌耐力、柔軟度、身體組成（口訣：心力耐柔組）。", "爆發力、敏捷、平衡、協調、速度、反應時間「不在」這籃，它們屬於競技體適能。"],
      "上班族爬樓梯不喘、搬東西不閃到腰，靠的就是健康體適能。", ["term-skill-fitness", "term-body-comp"], ["L22"], ["mn-wgmt-health5"]),
    t("term-skill-fitness", "競技體適能", ["技能體適能", "運動體適能"], "偏向運動表現、比賽需要的 6 項體能。",
      ["敏捷、協調、平衡、速度、爆發力、反應時間（口訣：敏協平、速爆反）。"],
      "籃球員切入、起跳、搶球都在用競技體適能。", ["term-health-fitness", "term-power", "term-agility"], ["L22"], ["mn-wgmt-sport6"]),
    t("term-body-comp", "身體組成", ["體脂率", "body composition"], "〔補充〕身體裡脂肪 vs 非脂肪（肌肉、骨頭、水分等）的比例。",
      ["健康體適能 5 項之一。"],
      "同樣 70 公斤，體脂 15% 跟 30% 的身體組成差很多。", ["term-health-fitness"], ["L22"], ["mn-wgmt-health5"]),
    t("term-power", "爆發力", ["power"], "很短時間內出很大的力（力量 × 速度）。",
      ["屬競技體適能，不是健康 5 項。"],
      "立定跳遠、跳起來搶籃板。", ["term-skill-fitness", "term-strength"], ["L22", "L21"], ["mn-wgmt-sport6"]),
    t("term-agility", "敏捷", ["agility"], "快速改變方向、位置的能力。",
      ["屬競技體適能。"], "打羽球前後左右快速移位。", ["term-skill-fitness"], ["L22"], ["mn-wgmt-sport6"], False),
    t("term-coordination", "協調", ["coordination"], "身體不同部位能不能配合得剛好。",
      ["屬競技體適能。"], "跳繩手腳節奏對得上。", ["term-skill-fitness"], ["L22"], ["mn-wgmt-sport6"], False),
    t("term-reaction", "反應時間", ["reaction time"], "從看到／聽到訊號，到身體開始動作的時間。",
      ["屬競技體適能。"], "聽到槍響起跑；看到球飛來立刻伸手。", ["term-skill-fitness"], ["L22"], ["mn-wgmt-sport6"], False),
    t("term-atp", "ATP", ["三磷酸腺苷"], "〔補充〕肌肉能「直接拿來用」的能量，像手上的現金。",
      ["身體存的 ATP 很少，所以要靠三大能量系統一直補。"],
      "三大能量系統＝三種把 ATP 補回來的方法。", ["term-pcr", "term-glycolysis", "term-aerobic-system"], ["L22"], ["mn-wgmt-energy"], False, ENERGY),
    t("term-pcr", "磷酸肌酸系統", ["ATP-CP", "ATP-PC", "磷酸肌酸", "磷化物系統", "磷酸原系統"], "最快的能量系統：燃料磷酸肌酸、無氧。",
      ["WG：最快，例子 100m 衝刺。很快就用完。"],
      "100 公尺衝刺、舉一次最大重量。", ["term-atp", "term-glycolysis"], ["L22"], ["mn-wgmt-energy"], True, ENERGY),
    t("term-glycolysis", "糖解", ["糖解系統", "醣解", "醣解系統", "糖酵解", "乳酸系統"], "把糖（肝醣、血糖）分解來產生能量。",
      ["WG：燃料肝醣、血糖；無氧（產生乳酸）／有氧；速度其次；例子 400m。", "肝醣代謝以無氧為主，血糖代謝以有氧為主。"],
      "跑 400 公尺最後腿灌鉛那種感覺。", ["term-glycogen", "term-blood-glucose", "term-lactate"], ["L22"], ["mn-wgmt-energy"], True, ENERGY),
    t("term-glycogen", "肝醣", ["肌醣", "glycogen"], "〔補充〕存在肝臟和肌肉裡的「糖的庫存」。",
      ["WG：糖解中，肝醣代謝以無氧為主。"],
      "像冰箱裡的存糧，需要時拿出來用。", ["term-glycolysis", "term-blood-glucose"], ["L22"], ["mn-wgmt-energy"], False),
    t("term-blood-glucose", "血糖", ["葡萄糖"], "血液裡流動的葡萄糖。",
      ["WG：糖解中，血糖代謝以有氧為主。"],
      "吃完飯血糖上升，身體會把它送去用或存起來。", ["term-glycolysis", "term-glycogen", "term-insulin-sens"], ["L22"], ["mn-wgmt-energy"], False),
    t("term-lactate", "乳酸", ["lactate"], "糖在無氧下快速分解時產生的物質。",
      ["WG：糖解無氧時產生乳酸；85–95% 心率區可提高代謝乳酸能力（無氧閾值）。"],
      "高強度連續做很多下，肌肉燒燒的時候。", ["term-glycolysis", "term-anaerobic-threshold"], ["L22", "L23"], ["mn-wgmt-energy"]),
    t("term-aerobic-system", "有氧系統", ["氧化系統", "有氧代謝"], "要用氧氣、最慢但最持久的能量系統。",
      ["WG：燃料醣、脂肪、蛋白質；例子 1000m 以上、慢跑。"],
      "像銀行帳戶：領錢慢，但錢很多。", ["term-pcr", "term-glycolysis"], ["L22"], ["mn-wgmt-energy"], True, ENERGY),
    t("term-aerobic-vs-anaerobic", "有氧 vs 無氧", ["無氧運動", "有氧運動"], "無氧＝不太需要氧氣、快但撐不久；有氧＝要用氧氣、慢但撐很久。",
      ["磷酸肌酸＝無氧；糖解＝無氧／有氧；有氧系統＝有氧。"],
      "衝刺偏無氧；慢跑偏有氧。", ["term-pcr", "term-aerobic-system"], ["L22"], ["mn-wgmt-energy"]),
    t("term-heart-rate", "心率", ["心跳", "bpm"], "心臟每分鐘跳幾下（bpm，次／分）。",
      ["〔補充〕量法：手腕拇指側摸脈搏，數 15 秒 × 4。"],
      "安靜坐著約 60–80 下算常見。〔補充〕", ["term-mhr", "term-rhr", "term-hrr", "term-thr"], ["L23"], ["mn-wgmt-hr-names"], True, HR),
    t("term-mhr", "最大心率", ["MHR", "Maximum Heart Rate"], "拚到極限時心臟最快能跳幾下。",
      ["〔補充：常見公式，影片未列公式〕MHR ≈ 220 − 年齡。", "影片 5 個心率區間用「%最大心率」切。"],
      "40 歲 → 220−40＝180 bpm（粗估）。", ["term-hrr", "term-hr-zones"], ["L23"], ["mn-wgmt-hr-names", "mn-wgmt-karvonen"], True, HR),
    t("term-rhr", "安靜心率", ["RHR", "靜止心率", "Resting Heart Rate"], "完全休息、放鬆時的心率。",
      ["〔補充〕建議早上剛醒、還沒下床時量。", "Karvonen 公式最後要「加回」它。"],
      "早上醒來躺著數到每分鐘 65 下 → RHR＝65。", ["term-hrr", "term-thr"], ["L23"], ["mn-wgmt-hr-names"]),
    t("term-hrr", "儲備心率", ["HRR", "Heart Rate Reserve", "可動用心率", "%HRR"], "可動用心率＝最大心率 − 安靜心率。",
      ["WG 影片：HRR＝可動用心率。", "FITT-VP 表心肺強度用 %HRR：中度 40～<60%、高強度 ≥60%。"],
      "薪水（MHR）− 房租（RHR）＝可自由花的錢（HRR）。", ["term-mhr", "term-rhr", "term-karvonen"], ["L23", "L24"], ["mn-wgmt-hr-names", "mn-wgmt-karvonen"], True, HR),
    t("term-thr", "目標心率", ["THR", "Target Heart Rate", "訓練心率"], "這次訓練希望心跳落在的數字。",
      ["〔補充公式〕Karvonen：THR＝(MHR−RHR)×強度%＋RHR；或 %MHR 法：THR＝MHR×強度%。"],
      "30 歲 RHR70 用 60% HRR → 142 bpm。", ["term-karvonen", "term-hrr"], ["L23"], ["mn-wgmt-karvonen"], True, HR),
    t("term-karvonen", "Karvonen 公式", ["Karvonen", "卡氏公式"], "〔補充：常見公式，影片未列公式〕用儲備心率算目標心率：THR＝HRR×%＋RHR。",
      ["步驟：① MHR＝220−年齡 ② HRR＝MHR−RHR ③ HRR×強度% ④ ＋RHR。口訣：先減、再乘、最後加回。", "最常錯：忘了加回 RHR。"],
      "50 歲、RHR80、40% → 170−80＝90 → ×0.4＝36 → ＋80＝116。", ["term-hrr", "term-thr"], ["L23", "L24"], ["mn-wgmt-karvonen"], True, HR),
    t("term-hr-zones", "心率區間", ["最大心率區間", "訓練區間"], "依 %最大心率分段，每段訓練效果不同。",
      ["WG：<55% 未達有效｜55–75% 有氧耐力｜75–85% 有氧動力｜85–95% 最大效能｜>95% 速度。", "站內講義另有一版切法，考題給哪張表就照哪張。"],
      "想熱身／減脂先在 55–75%；想提高無氧閾值用 85–95%。", ["term-mhr", "term-anaerobic-threshold", "term-vo2max"], ["L23"], ["mn-wgmt-zones5"], True, HR),
    t("term-anaerobic-threshold", "無氧閾值", ["anaerobic threshold"], "〔補充定義〕強度往上加到某點，乳酸開始堆得比清得快的轉折點。",
      ["WG：85–95% 最大心率（最大效能）可提高無氧閾值／代謝乳酸能力。", "閾值越高＝能用更高強度撐更久。常和「乳酸閾值」一起講。"],
      "以前配速 6 分就喘到不行，練完 5 分半還撐得住。", ["term-lactate", "term-hr-zones"], ["L23"], ["mn-wgmt-zones5"]),
    t("term-vo2max", "最大攝氧量", ["VO2max", "VO₂max", "攝氧量"], "〔補充定義〕身體每分鐘最多能吸收並使用的氧氣量，心肺能力的天花板。",
      ["WG：>95% 最大心率（速度區）提升攝氧量、最大攝氧量；屬間歇高強度、無法久。"],
      "耐力運動員的最大攝氧量通常很高。", ["term-hr-zones", "term-interval"], ["L23"], ["mn-wgmt-zones5"]),
    t("term-interval", "間歇訓練", ["間歇", "HIIT"], "高強度一段、休息一段，反覆進行。",
      ["WG：>95% 最大心率屬間歇高強度，無法持久。〔補充〕HIIT＝高強度間歇訓練。"],
      "衝刺 30 秒、走路 90 秒，重複 6 輪。", ["term-vo2max", "term-hr-zones"], ["L23"], ["mn-wgmt-zones5"], False),
    t("term-needs-analysis", "需求分析", ["需求評估"], "上課前先搞清楚客戶：要什麼、傷過什麼、程度多少。",
      ["WG 三點：① 客戶需求 ② 傷病史 ③ 體適能水準與訓練經驗。教官強調上課前非常重要。"],
      "像醫生先問診才開藥。", ["term-injury-history", "term-exercise-rx", "term-fittvp"], ["L24"], ["mn-wgmt-needs3"]),
    t("term-injury-history", "傷病史", [], "以前受過的傷、現在有的疾病。",
      ["需求分析三點之一；決定哪些動作要避開或調整。"],
      "膝蓋開過刀、高血壓、腰椎問題。", ["term-needs-analysis"], ["L24"], ["mn-wgmt-needs3"], False),
    t("term-exercise-rx", "運動處方", ["課表處方"], "依需求分析開出的「訓練配方」，常用 FITT-VP 寫。",
      ["需求分析＝問診；運動處方＝藥單。"],
      "每週 3 次、中強度快走 30 分……", ["term-fittvp", "term-needs-analysis"], ["L24"], ["mn-wgmt-fittvp"]),
    t("term-fittvp", "FITT-VP", ["FITTVP", "FITT", "FITT-VP 原則"], "開課表的六格：頻率、強度、時間、類型、總量、進展。",
      ["口訣：幾次、多用力、多久、練什麼、總共、怎麼加。", "影片：第二個 T＝模式、P＝進階；表格：第二個 T＝類型、P 欄標「模式／進展」。"],
      "客戶 A：每週 4 次、80%、1 小時、固定式器材、組×次×重量、每週／每月調整。", ["term-frequency", "term-intensity", "term-volume", "term-progression"], ["L24"], ["mn-wgmt-fittvp"], True, FITT),
    t("term-frequency", "頻率（F）", ["訓練頻率", "Frequency"], "一週練幾次。",
      ["表：心肺中強度≥5 次／高強度≥3 次／合併 3–5 次；阻力 2–3 次；柔軟度至少 2–3 次、每天最好。"],
      "每週一、三、五練＝頻率 3 次。", ["term-fittvp"], ["L24"], ["mn-wgmt-fittvp"]),
    t("term-intensity", "強度（I）", ["訓練強度", "Intensity"], "練多用力、負荷多重。",
      ["重訓常用 %1RM／%RM、自覺量表；心肺常用 %HRR（中度 40～<60%、高 ≥60%）；柔軟度拉到緊或輕微不適。", "7 因素之一：太高做不完、太低沒效。"],
      "80%1RM、60% HRR。", ["term-fittvp", "term-pct-1rm", "term-hrr"], ["L24", "L21"], ["mn-wgmt-fittvp"]),
    t("term-fitt-time", "時間（T）", [], "一次練多久。",
      ["表：心肺中強度 >30 分、高強度 20–25 分、合併 20–30 分；阻力無明確時間；靜態伸展 10–30 秒（老人 30–60 秒）。"],
      "一次 1 小時。", ["term-fittvp"], ["L24"], ["mn-wgmt-fittvp"], False),
    t("term-fitt-type", "類型／模式（T）", ["運動類型", "運動模式"], "練什麼方式；影片稱「模式」，表稱「類型」。",
      ["表：心肺＝有氧（快走、游泳、跳舞、滑步機）、負重運動；阻力＝機械、自由重量、壺鈴、藥球；柔軟度＝主動、被動伸展。"],
      "固定式器材、快走。", ["term-fittvp"], ["L24"], ["mn-wgmt-fittvp"]),
    t("term-volume", "總量（V）", ["訓練總量", "訓練量", "Volume"], "加起來總共練了多少。",
      ["重訓：組 × 次 × 重量（影片）；表上阻力寫組數、次數。心肺：每週 1000 大卡或 150 分鐘。柔軟度：每部位 60 秒。"],
      "3 組 × 10 下 × 40 公斤＝1200 公斤。", ["term-fittvp"], ["L24"], ["mn-wgmt-fittvp", "mn-wgmt-cardio-150"]),
    t("term-progression", "進展／進階（P）", ["漸進", "Progression"], "隨時間怎麼慢慢加量。",
      ["影片：強度、次數、頻率改變。表：心肺開始 4～6 週每 1～2 週加 5～10 分；阻力同肌群隔 48 小時、漸增阻力／RM／頻率；柔軟度每部位 2–4 次、肌溫高時最好。"],
      "第 1 週快走 20 分 → 第 3 週 30 分。", ["term-fittvp"], ["L24"], ["mn-wgmt-fittvp", "mn-wgmt-res-48"]),
    t("term-neuromotor", "神經動作訓練", ["神經動作", "neuromotor"], "〔補充〕平衡、協調、敏捷、本體感覺類的練習。",
      ["你提供的 FITT-VP 表上這列是「……」未填，本站不自行補數字。"],
      "單腳站、太極。", ["term-fittvp"], ["L24"], [], False),
    t("term-static-stretch", "靜態伸展", ["static stretching", "伸展時間", "伸展多久", "伸展幾秒"], "把肌肉拉到定點後停住不動。",
      ["表：保持 10–30 秒；老年人 30–60 秒；拉到緊或輕微不適；每部位累計 60 秒、2–4 次；肌溫高時效果最好。"],
      "坐姿前彎摸腳尖停 20 秒，做 3 次＝60 秒。", ["term-active-passive-stretch"], ["L24"], ["mn-wgmt-flex-time"]),
    t("term-active-passive-stretch", "主動伸展／被動伸展", ["主動伸展", "被動伸展"], "〔補充定義〕主動＝靠自己肌肉出力帶到伸展位；被動＝靠外力（夥伴、彈力帶、牆、重力）幫你拉。",
      ["FITT-VP 表柔軟度類型：主動、被動伸展等。"],
      "躺著自己抬腿＝主動；夥伴幫你推腿＝被動。", ["term-static-stretch"], ["L24"], ["mn-wgmt-flex-time"], False),
    t("term-kcal", "大卡", ["kcal", "卡路里"], "能量單位，日常說的「卡路里」。",
      ["FITT-VP 表心肺總量：每週 1000 大卡或 150 分鐘。"],
      "一週運動加起來消耗約 1000 大卡。", ["term-volume"], ["L24", "L09"], ["mn-wgmt-cardio-150"], False),
]
